import { Meta, Story } from '@storybook/react';
import { Circle as CircleComponent } from './circle.component';

export default {
  title: 'Components / Circle',
} as Meta;

export const Circle: Story = () => (
  <div className="flex flex-wrap gap-4">
    <CircleComponent
      borderColor="border-rainbow-010"
      textColor="text-rainbow-010"
    >
      010
    </CircleComponent>
    <CircleComponent
      borderColor="border-rainbow-020"
      textColor="text-rainbow-020"
    >
      020
    </CircleComponent>
    <CircleComponent
      borderColor="border-rainbow-030"
      textColor="text-rainbow-030"
    >
      030
    </CircleComponent>
    <CircleComponent
      borderColor="border-rainbow-040"
      textColor="text-rainbow-040"
    >
      040
    </CircleComponent>
    <CircleComponent
      borderColor="border-rainbow-050"
      textColor="text-rainbow-050"
    >
      050
    </CircleComponent>
    <CircleComponent
      borderColor="border-rainbow-060"
      textColor="text-rainbow-060"
    >
      060
    </CircleComponent>
    <CircleComponent
      borderColor="border-rainbow-070"
      textColor="text-rainbow-070"
    >
      070
    </CircleComponent>
    <CircleComponent
      borderColor="border-rainbow-080"
      textColor="text-rainbow-080"
    >
      080
    </CircleComponent>
    <CircleComponent
      borderColor="border-rainbow-090"
      textColor="text-rainbow-090"
    >
      090
    </CircleComponent>
    <CircleComponent
      borderColor="border-rainbow-100"
      textColor="text-rainbow-100"
    >
      100
    </CircleComponent>
    <CircleComponent
      borderColor="border-rainbow-110"
      textColor="text-rainbow-110"
    >
      110
    </CircleComponent>
    <CircleComponent
      borderColor="border-rainbow-120"
      textColor="text-rainbow-120"
    >
      120
    </CircleComponent>
    <CircleComponent
      borderColor="border-rainbow-130"
      textColor="text-rainbow-130"
    >
      130
    </CircleComponent>
    <CircleComponent
      borderColor="border-rainbow-140"
      textColor="text-rainbow-140"
    >
      140
    </CircleComponent>
    <CircleComponent
      borderColor="border-rainbow-150"
      textColor="text-rainbow-150"
    >
      150
    </CircleComponent>
    <CircleComponent
      borderColor="border-rainbow-160"
      textColor="text-rainbow-160"
    >
      160
    </CircleComponent>
  </div>
);
